# -*- coding: utf-8 -*-
"""Bam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rReSayZUiARSw0t1amkIeLfqWrSp-P1a
"""

import numpy as np

input_pattern=np.array([[1,-1,1],[-1,1,-1]])
output_pattern=np.array([[1,1],[-1,-1]])

weights=np.dot(input_pattern.T,output_pattern)

def recall(input_pattern):
  return np.sign(np.dot(input_pattern,weights))

test=np.array([[1,-1,1]])
result=recall(test)
print("THe recalled value is:",result)

retrieved=np.dot(result,weights.T)
retrieved=np.sign(retrieved)
print("The retrieved input is:", retrieved)



