# -*- coding: utf-8 -*-
"""evenodd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zi65UqI4aisESCctvip52y3k3btR8H04
"""

from sklearn.linear_model import Perceptron
import numpy as np

# Training data for even and odd ASCII values
X_train = np.array([
    [48, 0], [50, 0], [52, 0], [54, 0], [56, 0],  # Even ASCII values: '0', '2', '4', '6', '8'
    [49, 1], [51, 1], [53, 1], [55, 1], [57, 1]   # Odd ASCII values: '1', '3', '5', '7', '9'
])

# Target labels (0 for even, 1 for odd)
y_train = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
# Initialize and train the Perceptron model
model = Perceptron()
model.fit(X_train, y_train)



# Test the model with ASCII values of digits from 0 to 9
test_values = np.array([
    [53, 1], [50, 0], [48, 0], [55, 1], [52, 0]  # '5', '2', '0', '7', '4'
])


predictions = model.predict(test_values)
# Print the predictions
for value, prediction in zip(test_values[:, 0], predictions):
    if prediction == 0:
        print(f"ASCII value {value} is Even")
    else:
        print(f"ASCII value {value} is odd.")

import numpy as np
from sklearn.linear_model import Perceptron

X_train=np.array ([
    [48, 0], [50, 0], [52, 0], [54, 0], [56, 0],  # Even ASCII values: '0', '2', '4', '6', '8'
    [49, 1], [51, 1], [53, 1], [55, 1], [57, 1]
])

y_train =  np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

model=Perceptron()
model.fit(X_train,y_train)

test_values= np.array([
        [53, 1], [50, 0], [48, 0], [55, 1], [52, 0]  # '5', '2', '0', '7', '4'
])

predictions= model.predict(test_values)

for value, prediction in zip(test_values[ :,0], predictions):
    ascii_digit = chr(value)
    if prediction == 0:
      print(f"ASCII value {chr(value)} is Even")
    else:
      print(f"ASCII value {chr(value)} is odd.")

