# -*- coding: utf-8 -*-
"""tensorflolw9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wg7HSen1EXbEVNLWpWTnpNPeDlXhsL0l
"""







import tensorflow as tf
import numpy as np

np.random.seed(0)
x=np.random.rand(100,2)
y=np.random.randint(0,2,size=100)

model=tf.keras.Sequential([
    tf.keras.layers.Input(shape=(2,)),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x,y,epochs=100, verbose=10)

loss, accuracy=model.evaluate(x,y)
print(f"loss:{loss}, Accuracy:{accuracy}")
predictions = model.predict(x)
print("First 10 predictions:")
print(predictions[:10])

